"""Generate Croissant 1.1 metadata (with RAI extension) for the three published
Agentick oracle-trajectory datasets on HuggingFace.

Produces one *.croissant.json per dataset in this directory. The base
distribution / recordSet structure is fetched from HuggingFace's
auto-generated Croissant (validated by HF) so we inherit a valid file/field
schema; we then layer on hand-curated description, license, citation, and
the full Croissant RAI extension fields required by the 2026 CFP.

Run:  python croissant/_generate.py
Validate:  for f in croissant/*.croissant.json; do mlcroissant validate --jsonld "$f"; done
"""

from __future__ import annotations

import json
import urllib.request
from pathlib import Path

DATASETS = [
    "agentick-oracle-trajectories-120k",
    "agentick-oracle-trajectories-250k",
    "agentick-oracle-trajectories-500k",
]
OWNER = "anon-paper-submission"
GITHUB_REPO = "https://github.com/anonymousps3/agentick-anon-submission"
VERSION = "1.0.0"
DATE_PUBLISHED = "2026-04-16"

CITE_AS = (
    r"@software{agentick2025,"
    r" title={Agentick: Universal Benchmark for AI Agents},"
    r" author={Anonymous Author},"
    r" year={2025},"
    r" url={https://github.com/anonymousps3/agentick-anon-submission}}"
)

DESCRIPTION_TEMPLATE = (
    "Per-step oracle trajectories from the Agentick benchmark, a procedurally "
    "generated 2D gridworld suite for evaluating AI agents on navigation, "
    "memory, planning, reasoning, generalization, and multi-agent tasks. "
    "Each row records a single environment step taken by a deterministic "
    "task-specific oracle policy: the task name, episode/step index, "
    "difficulty level, ASCII and natural-language renderings of the "
    "observation, the action taken (name + integer index), the scalar reward, "
    "and a terminal flag. Train and test splits use disjoint deterministic "
    "seeds drawn from agentick.leaderboard.seeds.generate_task_seeds and are "
    "fully reproducible from the open-source codebase. This is the {scale} "
    "variant ({train_examples:,} train rows, {test_examples:,} test rows)."
)

# Croissant RAI extension (http://mlcommons.org/croissant/RAI/) — 2026 fields.
# All fields populated; demographic / annotator fields use the 'N/A with
# rationale' pattern the CFP FAQ asks for.
RAI = {
    "dataCollection": (
        "Synthetic. Trajectories are generated by running deterministic "
        "task-specific oracle policies (hand-coded reference solvers) against "
        "Gymnasium-compatible procedurally-generated Agentick environments. "
        "Each episode is seeded with a deterministic value from "
        "agentick.leaderboard.seeds.generate_task_seeds; train and test "
        "splits use disjoint seed pools. At each step the environment's "
        "ASCII-grid and natural-language renderings, the oracle's action, "
        "and the resulting reward and terminal flag are recorded. No human "
        "subjects, no scraping, no third-party data, no PII."
    ),
    "dataCollectionType": "Synthetic Data Generation",
    "dataCollectionTimeframe": {
        "@type": "sc:DateTime",
        "@value": "2026-04-16",
    },
    "dataPreprocessingProtocol": (
        "None beyond serialization: trajectory rows are written to Parquet "
        "with the schema declared above. Renders are stored as strings, "
        "actions as integer indices and human-readable names, rewards as "
        "float32, and terminal flags as booleans. No filtering, "
        "deduplication, balancing, or augmentation is applied. The complete "
        "preprocessing pipeline is "
        "examples/data_and_finetuning/collect_oracle_trajectories.py in the "
        "code repository."
    ),
    "dataAnnotationProtocol": (
        "Not applicable. Action labels are produced by deterministic oracle "
        "policies, not human annotators. Each task has exactly one oracle, "
        "so every row's action is fully determined by the task, environment "
        "seed, and step index — no annotation, adjudication, or "
        "inter-annotator agreement is involved."
    ),
    "dataAnnotationPlatform": "Not applicable — no human annotators.",
    "dataAnnotationAnalysis": "Not applicable — no human annotators.",
    "annotationsPerItem": "Not applicable — no human annotators.",
    "annotatorDemographics": (
        "Not applicable. This is a fully synthetic dataset produced by "
        "deterministic algorithmic policies; no human annotators were "
        "involved at any stage."
    ),
    "machineAnnotationTools": (
        "Per-task oracle policies in agentick.oracles (open-source, see code "
        "repository). Each oracle is a hand-implemented reference solver "
        "specific to one task family (e.g. shortest-path BFS for navigation "
        "tasks, dependency-respecting plan execution for key-door puzzles)."
    ),
    "personalSensitiveInformation": (
        "None. The dataset is procedurally generated synthetic content with "
        "no personal, demographic, biometric, location, financial, or "
        "otherwise sensitive information about any individual. No identifying "
        "data is collected or derivable."
    ),
    "dataBiases": (
        "Procedural-generation biases: the distribution over maze layouts, "
        "object placements, and difficulty parameters reflects the design "
        "choices of agentick.generation rather than a natural distribution. "
        "Behavioral bias: every action label comes from a single oracle per "
        "task, so models trained on this data will inherit oracle-specific "
        "tie-breaking choices (e.g. preferred direction in symmetric "
        "shortest-path situations). No demographic or human-population "
        "biases are present, because no human-population data is present."
    ),
    "dataLimitations": (
        "(1) Procedurally generated 2D gridworld trajectories — not "
        "representative of natural language, real-world imagery, or embodied "
        "robotics. (2) Optimal/near-optimal demonstrations only; the dataset "
        "contains no failure, exploration, or sub-optimal-policy data. "
        "(3) ASCII and language renderings follow fixed templates; they are "
        "not natural-language descriptions written by humans. "
        "(4) Generalization claims should be evaluated against the held-out "
        "test split (disjoint seeds), not held-out rows of the train split, "
        "since within-episode rows are highly correlated."
    ),
    "dataReleaseMaintenancePlan": (
        "Datasets are versioned by commit SHA on the HuggingFace Hub and the "
        "exact regeneration pipeline is in the open-source code repository "
        "(scripts/generate_datasets.sh + "
        "examples/data_and_finetuning/collect_oracle_trajectories.py). "
        "Anyone can reproduce or extend the data deterministically. No "
        "active maintenance commitment is made beyond the paper's review "
        "period; the codebase is sufficient for the community to maintain "
        "or evolve the data."
    ),
    "dataUseCases": (
        "Imitation learning / behavior cloning baselines for the Agentick "
        "benchmark; supervised fine-tuning of LLMs and VLMs on agentic "
        "decision-making tasks; offline reinforcement learning pretraining; "
        "studying sample efficiency of demonstration-based learners; "
        "ablations on observation modality (ASCII vs natural-language "
        "render). The dataset is intended exclusively for research on "
        "synthetic agent benchmarks."
    ),
    "dataSocialImpact": (
        "Low risk. The dataset enables research on agent learning in "
        "synthetic gridworld environments and has no direct mapping to "
        "real-world deployment scenarios. The primary misuse risk is "
        "benchmark gaming (training on test-split seeds), which is mitigated "
        "by the disjoint-seed train/test partition and by the leaderboard's "
        "use of further held-out evaluation seeds. No dual-use, safety, or "
        "fairness concerns are raised by the data itself."
    ),
}

# Per-dataset split row counts (from HF dataset_info; matches Parquet contents).
SPLITS = {
    "agentick-oracle-trajectories-120k": {"train": 120465, "test": 120430},
    "agentick-oracle-trajectories-250k": {"train": 251076, "test": 252123},
    "agentick-oracle-trajectories-500k": {"train": 505216, "test": 252123},
}
SCALES = {
    "agentick-oracle-trajectories-120k": "120k-step",
    "agentick-oracle-trajectories-250k": "250k-step",
    "agentick-oracle-trajectories-500k": "500k-step",
}


def fetch_hf_croissant(name: str) -> dict:
    url = f"https://huggingface.co/api/datasets/{OWNER}/{name}/croissant"
    with urllib.request.urlopen(url) as resp:
        return json.loads(resp.read())


def build(name: str) -> dict:
    base = fetch_hf_croissant(name)

    base["@context"]["rai"] = "http://mlcommons.org/croissant/RAI/"
    base["@context"]["prov"] = "http://www.w3.org/ns/prov#"
    base["@context"].setdefault("examples", {"@id": "cr:examples", "@type": "@json"})
    base["@context"].setdefault("samplingRate", "cr:samplingRate")
    base["@context"].setdefault("equivalentProperty", "cr:equivalentProperty")

    base["description"] = DESCRIPTION_TEMPLATE.format(
        scale=SCALES[name],
        train_examples=SPLITS[name]["train"],
        test_examples=SPLITS[name]["test"],
    )
    base["license"] = "https://spdx.org/licenses/MIT.html"
    base["citeAs"] = CITE_AS
    base["version"] = VERSION
    base["datePublished"] = DATE_PUBLISHED
    base["creator"] = {"@type": "Person", "name": "Anonymous Author"}
    base["sameAs"] = GITHUB_REPO
    base["keywords"] = [
        "reinforcement-learning", "imitation-learning", "behavior-cloning",
        "benchmark", "ai-agents", "gridworld", "synthetic", "oracle-trajectories",
    ]

    for field, value in RAI.items():
        base[f"rai:{field}"] = value

    base["rai:hasSyntheticData"] = True
    base["prov:wasGeneratedBy"] = {
        "@type": "prov:Activity",
        "prov:label": "Oracle trajectory collection",
        "prov:description": (
            "Each row was generated by running a deterministic per-task "
            "oracle policy in a procedurally-generated Agentick environment "
            "and recording the resulting (observation, action, reward, "
            "done) tuple. Train and test splits use disjoint deterministic "
            "seeds from agentick.leaderboard.seeds.generate_task_seeds."
        ),
        "prov:used": (
            f"{GITHUB_REPO}/blob/main/examples/data_and_finetuning/"
            "collect_oracle_trajectories.py"
        ),
    }

    return base


def main():
    out_dir = Path(__file__).parent
    for name in DATASETS:
        doc = build(name)
        path = out_dir / f"{name}.croissant.json"
        with open(path, "w") as f:
            json.dump(doc, f, indent=2)
            f.write("\n")
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
